"""empty message

Revision ID: 286b3c589a32
Revises: 9b7ec7b18cd4
Create Date: 2024-01-10 16:49:14.106264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286b3c589a32'
down_revision = '9b7ec7b18cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('enquiry', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('enquiry', sa.Column('address_line3', sa.String(), nullable=True))
    op.add_column('enquiry', sa.Column('address_number_or_name', sa.String(), nullable=True))
    op.add_column('enquiry', sa.Column('category', sa.String(), nullable=True))
    op.add_column('enquiry', sa.Column('category_detail', sa.String(), nullable=True))
    op.add_column('enquiry', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiry', 'status')
    op.drop_column('enquiry', 'category_detail')
    op.drop_column('enquiry', 'category')
    op.drop_column('enquiry', 'address_number_or_name')
    op.drop_column('enquiry', 'address_line3')
    op.drop_column('enquiry', 'address_line2')
    op.drop_column('enquiry', 'address_line1')
    # ### end Alembic commands ###
