"""empty message

Revision ID: a70947bbd281
Revises: 5bce28283e35
Create Date: 2024-01-12 14:40:32.140270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70947bbd281'
down_revision = '5bce28283e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiryactivity', sa.Column('enquiry_id', sa.Integer(), nullable=True))
    op.drop_constraint('enquiryactivity_enuiry_id_fkey', 'enquiryactivity', type_='foreignkey')
    op.create_foreign_key(None, 'enquiryactivity', 'enquiry', ['enquiry_id'], ['id'])
    op.drop_column('enquiryactivity', 'enuiry_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiryactivity', sa.Column('enuiry_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enquiryactivity', type_='foreignkey')
    op.create_foreign_key('enquiryactivity_enuiry_id_fkey', 'enquiryactivity', 'enquiry', ['enuiry_id'], ['id'])
    op.drop_column('enquiryactivity', 'enquiry_id')
    # ### end Alembic commands ###
