"""empty message

Revision ID: afe46037febc
Revises: a70947bbd281
Create Date: 2024-03-14 11:45:00.045860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe46037febc'
down_revision = 'a70947bbd281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
