"""empty message

Revision ID: b7122c210f67
Revises: 409e92d148e7
Create Date: 2024-01-02 14:34:54.947469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7122c210f67'
down_revision = '409e92d148e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry', sa.Column('postcode', sa.String(), nullable=True))
    op.alter_column('enquiry', 'company_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enquiry', 'company_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('enquiry', 'postcode')
    # ### end Alembic commands ###
